/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_leveldb_NativeLevelDb */

#ifndef _Included_com_google_leveldb_NativeLevelDb
#define _Included_com_google_leveldb_NativeLevelDb
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_options_create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1options_1create
  (JNIEnv *, jclass);

/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_options_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1options_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_options_set_create_if_missing
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1options_1set_1create_1if_1missing
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_options_set_write_buffer_size
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1options_1set_1write_1buffer_1size
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_options_set_cache
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1options_1set_1cache
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_writeoptions_create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1writeoptions_1create
  (JNIEnv *, jclass);

/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_writeoptions_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1writeoptions_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_writeoptions_set_sync
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1writeoptions_1set_1sync
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_open
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1open
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_put
 * Signature: (JJLjava/nio/ByteBuffer;JLjava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1put
  (JNIEnv *, jclass, jlong, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_readoptions_create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1readoptions_1create
  (JNIEnv *, jclass);

/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_readoptions_set_verify_checksums
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1readoptions_1set_1verify_1checksums
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_readoptions_set_fill_cache
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1readoptions_1set_1fill_1cache
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_readoptions_set_snapshot
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1readoptions_1set_1snapshot
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_readoptions_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1readoptions_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_create_snapshot
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1create_1snapshot
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_release_snapshot
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1release_1snapshot
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_get
 * Signature: (JJLjava/nio/ByteBuffer;J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1get
  (JNIEnv *, jclass, jlong, jlong, jobject, jlong);

/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_exists
 * Signature: (JJLjava/nio/ByteBuffer;J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1exists
  (JNIEnv *, jclass, jlong, jlong, jobject, jlong);

/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_delete
 * Signature: (JJLjava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1delete
  (JNIEnv *, jclass, jlong, jlong, jobject, jlong);

/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_cache_create_lru
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1cache_1create_1lru
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_cache_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1cache_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_writebatch_create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1writebatch_1create
  (JNIEnv *, jclass);

/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_writebatch_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1writebatch_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_writebatch_clear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1writebatch_1clear
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_writebatch_put
 * Signature: (JLjava/nio/ByteBuffer;JLjava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1writebatch_1put
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_writebatch_delete
 * Signature: (JLjava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1writebatch_1delete
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_write
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1write
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_filterpolicy_create_bloom
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1filterpolicy_1create_1bloom
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_filterpolicy_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1filterpolicy_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_google_leveldb_NativeLevelDb
 * Method:    leveldb_options_set_filter_policy
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_google_leveldb_NativeLevelDb_leveldb_1options_1set_1filter_1policy
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
