/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_softwareverde_bitcoin_jni_bin_NativeUnspentTransactionOutputCache */

#ifndef _Included_com_softwareverde_bitcoin_jni_bin_NativeUnspentTransactionOutputCache
#define _Included_com_softwareverde_bitcoin_jni_bin_NativeUnspentTransactionOutputCache
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_softwareverde_bitcoin_jni_bin_NativeUnspentTransactionOutputCache
 * Method:    _init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_softwareverde_bitcoin_jni_bin_NativeUnspentTransactionOutputCache__1init
  (JNIEnv *, jclass);

/*
 * Class:     com_softwareverde_bitcoin_jni_bin_NativeUnspentTransactionOutputCache
 * Method:    _destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_softwareverde_bitcoin_jni_bin_NativeUnspentTransactionOutputCache__1destroy
  (JNIEnv *, jclass);

/*
 * Class:     com_softwareverde_bitcoin_jni_bin_NativeUnspentTransactionOutputCache
 * Method:    _createCache
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_softwareverde_bitcoin_jni_bin_NativeUnspentTransactionOutputCache__1createCache
  (JNIEnv *, jclass);

/*
 * Class:     com_softwareverde_bitcoin_jni_bin_NativeUnspentTransactionOutputCache
 * Method:    _deleteCache
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_softwareverde_bitcoin_jni_bin_NativeUnspentTransactionOutputCache__1deleteCache
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_softwareverde_bitcoin_jni_bin_NativeUnspentTransactionOutputCache
 * Method:    _cacheUnspentTransactionOutputId
 * Signature: (I[BIJ)V
 */
JNIEXPORT void JNICALL Java_com_softwareverde_bitcoin_jni_bin_NativeUnspentTransactionOutputCache__1cacheUnspentTransactionOutputId
  (JNIEnv *, jclass, jint, jbyteArray, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
